version: "3.3"
services:
    mongo:
        image: mongo
        restart: unless-stopped
        env_file:
            - ./stack.env
        ports:
            - "28017:27017"
        volumes:
            - database:/data/db/

    userui:
      image: malyyigor34/15min-user-ui:main
      restart: unless-stopped
      ports:
        - "9093:3000"
      env_file:
          - ./stack.env
      healthcheck:
        test: ["CMD", "ping", "-c", "1", "-W", "1", "127.0.0.1:3000"]
        interval: 1s
        timeout: 5s
        retries: 50


    userapi:
      image: malyyigor34/15_min_user_api:master
      restart: unless-stopped
      ports:
        - "8511:8001"
      env_file:
        - ./stack.env

      healthcheck:
        test: ["CMD", "ping", "-c", "1", "-W", "1", "127.0.0.1:8001"]
        interval: 1s
        timeout: 5s
        retries: 50

volumes:
    database:
